// frontend/src/app/quiz_grammar/page.tsx

"use client";

import React, { useState, useEffect, useCallback } from "react"; 
import { useRouter, useSearchParams } from 'next/navigation'; 
import { Loader2 } from "lucide-react"
import { useCountdown } from "../hooks/useCountdown";
import Sidebar from "../test/quiz/components/Sidebar"; 
import QuestionContent from "../test/quiz/components/QuestionContent";
import LoadingModal from "../../components/ui/LoadingModal"; 
import toast from "react-hot-toast"; 

const SUBMIT_API_BASE_URL = 'http://127.0.0.1:8000/api/quiz-grammar'; 

interface Question {
    id: number;
    question_text: string;
    options: string[];
    correct_answer: string; 
}

export default function QuizPage() {
    const router = useRouter();
    const searchParams = useSearchParams(); 
    const sessionId = searchParams.get('sessionId'); 

    const [shuffledQuestions, setShuffledQuestions] = useState<Question[]>([]); 
    const [isLoading, setIsLoading] = useState(true); 
    const [showLoading, setShowLoading] = useState(false);
    const [statusMessage, setStatusMessage] = useState<string>("Đang tải dữ liệu phiên làm bài..."); 
    
    const [currentQuestion, setCurrentQuestion] = useState(1);
    const [selectedOptions, setSelectedOptions] = useState<Record<number, string>>({}); 
    const [currentUserId, setCurrentUserId] = useState<string | null>(null); 
    
    const { minutes, seconds } = useCountdown(10 * 60); 


    // --- LOGIC TẢI CÂU HỎI VÀ KIỂM TRA TRẠNG THÁI (POLLING LOGIC) ---
    // ✅ THAY ĐỔI: Hàm này trả về true để STOP polling nếu thành công HOẶC gặp lỗi nghiêm trọng
    const fetchQuestions = useCallback(async (token: string): Promise<boolean> => {
        if (!sessionId) return true; // Dừng polling nếu không có session ID
        
        try {
            const response = await fetch(`${SUBMIT_API_BASE_URL}/${sessionId}/questions`, {
                headers: { "Authorization": `Bearer ${token}` }
            });

            if (!response.ok) {
                const errorData = await response.json(); 
                const status = response.status;
                const detail = errorData.detail || `Lỗi ${status}`;

                if (status === 404 || status === 403) {
                    // Lỗi phiên không tồn tại/không có quyền truy cập
                    setStatusMessage("Phiên làm bài không tồn tại hoặc đã lỗi.");
                    toast.error(detail);
                    router.push('/roadmap'); 
                    return true; // 🚨 STOP POLLING
                }
                
                // 🚨 FIX LỖI 429/500: Lỗi API tạo bài
                if (status === 429 || status >= 500) {
                    setStatusMessage("Lỗi máy chủ/Quota. Vui lòng thử lại sau.");
                    toast.error(`Lỗi API (${status}): ${detail}`);
                    return true; // 🚨 STOP POLLING
                }
                
                // Lỗi tạm thời, tiếp tục thử lại
                setStatusMessage(`Lỗi kết nối (${status}). Đang thử lại...`);
                return false; 
            }
            
            const data = await response.json(); 
            const questions = data || [];

            if (questions.length > 0) {
                setShuffledQuestions(questions);
                setStatusMessage("Bài kiểm tra đã sẵn sàng!");
                return true; // ✅ THÀNH CÔNG: STOP POLLING
            } else {
                setStatusMessage("The test is being generated by AI. Please wait…");
                return false; // Chưa sẵn sàng, tiếp tục polling
            }

        } catch (e) {
            // Lỗi mạng hoặc lỗi parsing
            setStatusMessage(`Lỗi tải: ${e instanceof Error ? e.message : 'Không xác định'}`);
            // Chúng ta vẫn return false để thử lại sau 5s, trừ khi có logic chặn khác
            return false; 
        } finally {
            setIsLoading(false);
        }
    }, [sessionId, router]);


    // --- EFFECT CHÍNH: POLLING VÀ XÁC THỰC ---
    useEffect(() => {
        const userId = localStorage.getItem('authenticatedUserId');
        const token = localStorage.getItem('access_token');
        
        // 1. XÁC THỰC
        if (!userId || !token) {
            toast.error("Vui lòng đăng nhập lại để làm bài kiểm tra.");
            router.push('/auth');
            return;
        }
        setCurrentUserId(userId);

        // 2. POLLING LOGIC
        let interval: NodeJS.Timeout | null = null;
        
        if (sessionId) {
            // Lần gọi đầu tiên (không cần async IIFE vì đã có wrapper)
            fetchQuestions(token); 
            
            interval = setInterval(async () => {
                const finished = await fetchQuestions(token);
                if (finished) {
                    // ✅ NGỪNG POLLING khi thành công hoặc gặp lỗi nghiêm trọng (429/500)
                    clearInterval(interval!); 
                }
            }, 5000); 
            
        } else {
            toast.error("Thiếu ID bài kiểm tra.");
            router.push('/roadmap'); 
            setIsLoading(false);
        }
        
        return () => {
            if (interval) clearInterval(interval);
        };
        
    }, [router, sessionId, fetchQuestions]); // Thêm fetchQuestions vào dependency


    const handleSubmit = async () => {
        // ... (Logic handleSubmit giữ nguyên) ...
        if (!currentUserId || !sessionId || shuffledQuestions.length === 0) {
            toast.error("Bài làm không hợp lệ hoặc lỗi xác thực.");
            return;
        }
        
        setShowLoading(true);
        const token = localStorage.getItem('access_token');
        
        const mcqAnswers: Record<number, string> = {}; 

        Object.entries(selectedOptions).forEach(([qId, answer]) => {
            if (typeof answer === 'string' && answer !== null) {
                mcqAnswers[parseInt(qId)] = answer; 
            } 
        });

        const payload = {
            session_id: parseInt(sessionId), 
            user_id: currentUserId,
            answers: mcqAnswers, 
        };
        
        // --- Gửi Submission ---
        try {
            toast.loading("Đang chấm điểm và cập nhật tiến độ...", { id: 'analysis-loading' });

            const response = await fetch(`${SUBMIT_API_BASE_URL}/${sessionId}/submit`, { 
                method: 'POST',
                headers: { "Content-Type": "application/json", "Authorization": `Bearer ${token}` },
                body: JSON.stringify(payload)
            });
            
            toast.dismiss('analysis-loading');

            if (!response.ok) {
                const errorData = await response.json(); 
                throw new Error(errorData.detail || `Lỗi Server ${response.status}.`);
            }

            const results = await response.json(); 
            
            toast.success(`Nộp bài hoàn tất! Điểm của bạn: ${(results.score_percent * 100).toFixed(0)}%.`);
            
            setTimeout(() => {
               router.push(`/quiz_grammar/results?sessionId=${sessionId}`);
            }, 800);

        } catch (error) {
            let errorMessage = 'Gửi bài làm thất bại.';
            if (error instanceof Error) { errorMessage = error.message; }
            
            toast.dismiss('analysis-loading');
            toast.error(`Lỗi: ${errorMessage}`);
        } finally {
            setShowLoading(false);
        }
    };
    
    // Logic Loading / Status Message
    if (isLoading || shuffledQuestions.length === 0) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-gray-50">
                <div className="text-center">
                    {/* ✅ HIỂN THỊ SPINNER khi đang tải */}
                    {isLoading && <Loader2 className="w-8 h-8 animate-spin mx-auto mb-3 text-blue-500" />} 
                    <p className="text-lg text-gray-600">
                        {statusMessage} 
                    </p>
                </div>
            </div>
        );
    }
    
    const currentQ = shuffledQuestions[currentQuestion - 1];
    const currentAnswer = selectedOptions[currentQ?.id] || null; 

    return (
        <main className="min-h-screen bg-gray-50 py-8 px-6">
            {showLoading && (
                <LoadingModal
                    title="Grading and Analyzing..."
                    message="Evaluating your results and updating progress. Please wait."
                />
            )}

            <div className="flex max-w-7xl mx-auto gap-6">
                
                {/* Sidebar */}
                <Sidebar
                    shuffledQuestions={shuffledQuestions}
                    currentQuestion={currentQuestion}
                    selectedOptions={selectedOptions}
                    setCurrentQuestion={setCurrentQuestion}
                    minutes={minutes}
                    seconds={seconds}
                    onSubmit={handleSubmit}
                />

                {/* Question Area */}
                <div className="flex-1 flex justify-center">
                    <QuestionContent
                        currentQ={currentQ}
                        currentAnswer={currentAnswer}
                        setSelectedOptions={setSelectedOptions as any}
                        currentQuestion={currentQuestion}
                    />
                </div>

            </div>
        </main>
    );
}